---
version: '3.7'

services:
  sector-ui:
    image: mdas/sector-ui
    restart: on-failure
    ports:
      - "9091:80"
    environment:
      - SERVER_URL=ui-backend:8080
    volumes:
      - ./ui/sector-ui/build:/build

  ui-backend:
    image: mdas/ui-backend
    container_name: ui-backend
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "8082:8080"
      - "5004:5000"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  postgres:
    image: postgres
    container_name: postgres-container
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword

  data-science-service:
    container_name: data-science-interface
    build:
      context: services/data-science-service
    ports:
      - "8083:8080"
    environment:
      - CONTRACT_TEST=false
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

volumes:
  es-data:
