FROM python:3.7

COPY . /app
RUN mkdir data
WORKDIR /app
RUN pip install --upgrade pip && pip install -r requirements.txt
RUN python -m nltk.downloader stopwords

ENTRYPOINT python vectorize.py -p -v $MODEL_VERSION
