environment: local

spring:
  data:
    rest:
      detection-strategy: ANNOTATED
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: mysecretpassword
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

server:
  port: 8080

---

spring.profiles: local

data.science.service.baseurl: http://data-science-interface:8080

---

spring.profiles: embedded

---

spring.profiles: contractTests


# use static DS endpoint when running for contract tests
data.science.service.baseurl: http://data-science-interface:8080

---

spring.profiles: ft
---

spring.profiles: dev
---

spring.profiles: qa
---

spring.profiles: prod
