app:
  aws:
    region: us-east-1
    accessKeyId: FAKEACCESSKEY
    secretAccessKey: FAKESECRET
    bucketName: rdso-challenge2
    folder: data/movies_json
  jwt:
    secret: secret
  business:
    user:
      username: business-user
      password: password
    supervisor:
      username: business-supervisor
      password: password
  system:
    user:
      username: system-user
      password: password

data.science.service.baseurl: http://data-science-interface:8080/api/v1

logging:
  level:
    group.u: DEBUG
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %logger.%M - %msg%n"

info:
  version: ${platform.version}

elasticsearch:
  clustername: docker-cluster
  host: http://localhost
  port: 9200

cloud:
  aws:
    region:
      static: us-east-2
    stack:
      auto: false

environment: local

spring:
  data:
    rest:
      detection-strategy: ANNOTATED
    jest:
      uri: http://localhost:9200

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

---

spring.profiles: local

data.science.service.baseurl: http://data-science-interface:8080/api/v1

---

spring.profiles: contractTests


# use static DS endpoint when running for contract tests
data.science.service.baseurl: http://data-science-interface:8080/api/v1

---

spring.profiles: embedded
